[2018-04-24 20:00:29,373] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9094 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:00:29,400] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9092 (id: 0 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:00:29,404] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:00:59,479] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9094 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:00:59,506] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9092 (id: 0 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:00:59,513] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:01:29,590] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9094 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:01:29,614] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9092 (id: 0 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:01:29,623] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:01:33,256] TRACE [Controller id=2] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
[2018-04-24 20:01:33,262] DEBUG [Controller id=2] Preferred replicas by broker Map(2 -> Map(wing-binlog-event-1 -> Vector(2, 0, 1)), 1 -> Map(wing-binlog-event-0 -> Vector(1, 2, 0)), 0 -> Map(__consumer_offsets-49 -> Vector(0), __consumer_offsets-38 -> Vector(0), __consumer_offsets-16 -> Vector(0), __consumer_offsets-27 -> Vector(0), __consumer_offsets-8 -> Vector(0), __consumer_offsets-19 -> Vector(0), __consumer_offsets-13 -> Vector(0), __consumer_offsets-2 -> Vector(0), __consumer_offsets-46 -> Vector(0), __consumer_offsets-35 -> Vector(0), __consumer_offsets-24 -> Vector(0), __consumer_offsets-5 -> Vector(0), __consumer_offsets-43 -> Vector(0), __consumer_offsets-21 -> Vector(0), __consumer_offsets-32 -> Vector(0), __consumer_offsets-10 -> Vector(0), __consumer_offsets-37 -> Vector(0), __consumer_offsets-48 -> Vector(0), __consumer_offsets-29 -> Vector(0), __consumer_offsets-18 -> Vector(0), __consumer_offsets-40 -> Vector(0), __consumer_offsets-7 -> Vector(0), __consumer_offsets-45 -> Vector(0), __consumer_offsets-23 -> Vector(0), __consumer_offsets-34 -> Vector(0), __consumer_offsets-26 -> Vector(0), __consumer_offsets-4 -> Vector(0), __consumer_offsets-15 -> Vector(0), __consumer_offsets-42 -> Vector(0), __consumer_offsets-31 -> Vector(0), __consumer_offsets-9 -> Vector(0), __consumer_offsets-20 -> Vector(0), __consumer_offsets-12 -> Vector(0), __consumer_offsets-1 -> Vector(0), __consumer_offsets-28 -> Vector(0), __consumer_offsets-17 -> Vector(0), __consumer_offsets-6 -> Vector(0), __consumer_offsets-39 -> Vector(0), __consumer_offsets-44 -> Vector(0), __consumer_offsets-36 -> Vector(0), __consumer_offsets-47 -> Vector(0), __consumer_offsets-3 -> Vector(0), __consumer_offsets-25 -> Vector(0), __consumer_offsets-14 -> Vector(0), __consumer_offsets-30 -> Vector(0), __consumer_offsets-41 -> Vector(0), wing-binlog-event-2 -> Vector(0, 1, 2), __consumer_offsets-11 -> Vector(0), __consumer_offsets-33 -> Vector(0), __consumer_offsets-22 -> Vector(0), __consumer_offsets-0 -> Vector(0))) (kafka.controller.KafkaController)
[2018-04-24 20:01:33,262] DEBUG [Controller id=2] Topics not in preferred replica for broker 2 Map() (kafka.controller.KafkaController)
[2018-04-24 20:01:33,262] TRACE [Controller id=2] Leader imbalance ratio for broker 2 is 0.0 (kafka.controller.KafkaController)
[2018-04-24 20:01:33,262] DEBUG [Controller id=2] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
[2018-04-24 20:01:33,262] TRACE [Controller id=2] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)
[2018-04-24 20:01:33,263] DEBUG [Controller id=2] Topics not in preferred replica for broker 0 Map() (kafka.controller.KafkaController)
[2018-04-24 20:01:33,263] TRACE [Controller id=2] Leader imbalance ratio for broker 0 is 0.0 (kafka.controller.KafkaController)
[2018-04-24 20:01:59,699] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9094 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:01:59,721] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9092 (id: 0 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:01:59,737] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:02:29,809] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9094 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:02:29,828] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9092 (id: 0 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:02:29,844] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:02:59,917] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9094 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:02:59,935] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9092 (id: 0 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2018-04-24 20:02:59,956] WARN [RequestSendThread controllerId=2] Controller 2's connection to broker 192.168.0.105:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:272)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
